In [17]:
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
import numpy as np

# Sample data (replace this with your actual data)
data = {
    'Animal_ID': np.tile(['A', 'B', 'C', 'D'], 3),  # Animal IDs
    'Protocol': np.repeat(['Protocol1', 'Protocol2', 'Protocol3'], 4),  # Protocol names
    'Neural_Response': [10, 15, 12, 8, 12, 11, 13, 14, 12, 7, 7, 9]  # Neural response values
}

# Create a pandas DataFrame from the sample data
df = pd.DataFrame(data)

# # Convert Animal_ID and Protocol to categorical variables
df['Animal_ID'] = pd.Categorical(df['Animal_ID'])
df['Protocol'] = pd.Categorical(df['Protocol'],  categories=['Protocol3', 'Protocol1', 'Protocol2'], ordered=True)

print(df.head(8), '\n\n')

# Fit a mixed-effects model
mixed_lm = smf.mixedlm("Neural_Response ~ Protocol", df, groups=df["Animal_ID"])
mixed_lm_fit = mixed_lm.fit()

# Print the summary of the model
print(mixed_lm_fit.summary())


  Animal_ID   Protocol  Neural_Response
0         A  Protocol1               10
1         B  Protocol1               15
2         C  Protocol1               12
3         D  Protocol1                8
4         A  Protocol2               12
5         B  Protocol2               11
6         C  Protocol2               13
7         D  Protocol2               14 


            Mixed Linear Model Regression Results
Model:             MixedLM Dependent Variable: Neural_Response
No. Observations:  12      Method:             REML           
No. Groups:        4       Scale:              5.3889         
Min. group size:   3       Log-Likelihood:     -22.4294       
Max. group size:   3       Converged:          Yes            
Mean group size:   3.0                                        
--------------------------------------------------------------
                      Coef. Std.Err.   z   P>|z| [0.025 0.975]
--------------------------------------------------------------
Intercept           

/home/tplas/anaconda3/envs/s1s2mech/lib/python3.10/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/home/tplas/anaconda3/envs/s1s2mech/lib/python3.10/site-packages/statsmodels/regression/mixed_linear_model.py:2201: ConvergenceWarning: Retrying MixedLM optimization with lbfgs
  warnings.warn(
/home/tplas/anaconda3/envs/s1s2mech/lib/python3.10/site-packages/statsmodels/regression/mixed_linear_model.py:2238: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/home/tplas/anaconda3/envs/s1s2mech/lib/python3.10/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)


In [20]:
tmp = np.arange(10).reshape(2, 5)
print(tmp)
print(tmp.shape)
print(tmp.flatten())

## Use tile for the first dimension and repeat for the second dimension, see below:

[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
[0 1 2 3 4 5 6 7 8 9]


In [22]:
np.repeat(['a', 'b'], 5)

array(['a', 'a', 'a', 'a', 'a', 'b', 'b', 'b', 'b', 'b'], dtype='<U1')

In [23]:
np.tile(['a', 'b'], 5)

array(['a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b'], dtype='<U1')